name: athlo_app_novo
description: Aplicativo de comunidades esportivas – Projeto TCC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (mesma geração p/ evitar conflitos)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Login social
  google_sign_in: ^6.2.1

  # Manipulação de arquivos e mídia
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  record: ^6.1.1
  record_linux: ^1.2.1
  permission_handler: ^12.0.1

  # Player de áudio
  audioplayers: ^6.1.0

  # Outros utilitários
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.0

  # Mantendo compatibilidade da interface do record
  record_platform_interface: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loggin_itch.png
    - assets/images/image.png
    - assets/images/logo.png
    - assets/images/
    # Adicione outras imagens/ícones aqui futuramente:
    # - assets/images/
    # - assets/icons/
